/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dfftw.h> header file. */
/* #undef HAVE_DFFTW_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <drfftw.h> header file. */
/* #undef HAVE_DRFFTW_H */

/* Define to 1 if you have the <fftw.h> header file. */
#define HAVE_FFTW_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if you have libfhgjournaline */
/* #undef HAVE_JOURNALINE */

/* Define to 1 if you have the <journaline/NML.h> header file. */
/* #undef HAVE_JOURNALINE_NML_H */

/* Define to 1 if you have the `asound' library (-lasound). */
/* #undef HAVE_LIBASOUND */

/* Define to 1 if you have the `faac' library (-lfaac). */
/* #undef HAVE_LIBFAAC */

/* Define to 1 if you have the `faad' library (-lfaad). */
#define HAVE_LIBFAAD 1

/* Define to 1 if you have the `freeimage' library (-lfreeimage). */
/* #undef HAVE_LIBFREEIMAGE */

/* Define to 1 if you have the `hamlib' library (-lhamlib). */
/* #undef HAVE_LIBHAMLIB */

/* Define to 1 if you have the `qt-mt' library (-lqt-mt). */
/* #undef HAVE_LIBQT_MT */

/* Define to 1 if you have the `qwt' library (-lqwt). */
/* #undef HAVE_LIBQWT */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <rfftw.h> header file. */
#define HAVE_RFFTW_H 1

/* Define if you have Hamlib >= 1.2.1 */
/* #undef HAVE_RIG_PARSE_MODE */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
//#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "drm"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if you want to use the ALSA audio lib */
/* #undef USE_ALSA */

/* Define if you want to use /dev/dsp for sound */
/* #undef USE_DEVDSP */

/* Define if you want to use the faad2 library */
#define USE_FAAD2_LIBRARY 1

/* Define if you want to use the QT GUI */
/* #undef USE_QT_GUI */

/* Version number of package */
#define VERSION "1.2.4"

/* Define if you want to use sound */
/* #undef WITH_SOUND */
